name: Weekly Ticker Update Pipeline

# Trigger: every Saturday at 00:00 UTC
on:
  schedule:
    - cron: "0 0 * * 6" # At 00:00 on Saturdays
  workflow_dispatch:    # optional: allow manual trigger from Actions tab

jobs:
  index-sync:
    runs-on: ubuntu-slim
    permissions:
      contents: write    # needed to push changes back to the repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0         # full history, needed for commits
          persist-credentials: true  # ensures GITHUB_TOKEN is used for pushes

      - name: Set up Python 3.14
        uses: actions/setup-python@v6
        with:
          python-version: "3.14"

      - name: Install dependencies
        working-directory: pipeline
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run updater script
        working-directory: pipeline
        run: |
          source .venv/bin/activate
          python3 exchange-scraper.py

      - name: Check for changes
        id: git_diff
        run: |
          git add -A
          git status
          git diff --stat

          if git diff --staged --quiet; then
            echo "changed=false" >> $GITHUB_OUTPUT
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi
    
      - name: Commit and push changes
        if: steps.git_diff.outputs.changed == 'true'
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          git commit -m 'ci: update ticker files [skip ci]'
          git push origin HEAD

